apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "php-nginx-app.fullname" . }}-nginx-config
  labels:
    {{- include "php-nginx-app.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- .Values.nginx.config | nindent 4 }}